[IN-1659] Update openjdk from 8 to 11
bitrise-io/osx-box-bootstrap pull request #288
Opened 2020-08-19 07:42 UTC by fehersanyi-bitrise

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2020-08-19 07:47 UTC, peterheja-bitrise approved these changes
lgtm

2020-08-19 09:17 UTC, bitrise-tom approved these changes

2020-08-19 13:09 UTC, bitrise-tom approved these changes

2020-08-19 20:22 UTC, lmesz-bitrise requested changes

2020-08-19 20:22 UTC, lmesz-bitrise commented on roles/android/defaults/main.yml
> +sdkmanager_path: /usr/local/share/android-sdk/cmdline-tools/tools/bin/sdkmanager
I have the same concern that I added in case of android. (and you can use android_home as a prefix)

2020-08-19 20:22 UTC, lmesz-bitrise commented on roles/android/tasks/main.yml
> -  shell: "(echo y | sdkmanager --verbose '{{ item }}') || (echo y | sdkmanager --verbose '{{ item }}')"  # noqa 204 306
👍

2020-08-24 12:27 UTC, peterheja-bitrise approved these changes
lgtm

2020-08-24 15:00 UTC, lmesz-bitrise approved these changes
Please wait with the merge till https://github.com/bitrise-io/osx-box-bootstrap/pull/286/ PR.

2020-08-25 09:55 UTC, merged