[IN-1686] Install community requested tools
bitrise-io/osx-box-bootstrap pull request #296
Opened 2020-08-28 09:40 UTC by fehersanyi-bitrise

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2020-08-28 09:54 UTC, MrBlaise commented on roles/weekly-update-shared/defaults/main.yml
> +    version: "0.8.1"
```suggestion
  - name: "xcbeautify"
    version: "0.8.1"
```

Duplicate packages

2020-08-28 09:56 UTC, MrBlaise commented on roles/weekly-update-shared/tests/test_weekly_update_shared.py
> +    maxfiles = host.file("/Library/LaunchDaemons/imit.maxfiles.plist")
```suggestion
    maxfiles = host.file("/Library/LaunchDaemons/limit.maxfiles.plist")
```

2020-08-28 09:56 UTC, MrBlaise commented on roles/weekly-update-shared/tests/test_weekly_update_shared.py
> +    maxproc = host.file("/Library/LaunchDaemons/imit.maxproc.plist")
```suggestion
    maxproc = host.file("/Library/LaunchDaemons/limit.maxproc.plist")
```

2020-08-28 09:57 UTC, MrBlaise requested changes
see my comments

2020-08-28 10:59 UTC, peterheja-bitrise commented
Please, do not merge it until the end of weekly updates

2020-08-28 11:10 UTC, fehersanyi-bitrise commented
@MrBlaise @peter-bitrise my dudes this is still work in progress

2020-08-28 11:20 UTC, MrBlaise commented
> @MrBlaise @peter-bitrise my dudes this is still work in progress

@fehersanyi-bitrise You can convert the PR to draft (under the reviewers section)

2020-09-01 13:07 UTC, fehersanyi-bitrise commented
Sorry for the big PR :/

2020-09-01 14:45 UTC, bitrise-tom requested changes

2020-09-01 14:45 UTC, bitrise-tom commented on roles/bitrise-cli/tasks/main.yml
> +- name: Lookup ansible_distribution
here you can use `ansible_system` that is builtin to ansible's variables

2020-09-01 14:45 UTC, bitrise-tom commented on roles/bitrise-cli/tasks/main.yml
> +- name: clean up previous 'bitrise'
I don't like these three removal steps. 
I understand the logic behind them, but I think they are unnecessary.

The following downloads should work, and if they don't we should have an molecule test that runs the cli and makes sure the correct version is installed

2020-09-01 14:45 UTC, bitrise-tom commented on roles/bitrise-cli/tests/test_bitrise_cli.py
> +def test_bitrise_cli_exists(host):
these tests should check the version output from the tools, not just the existence of the binary

2020-09-01 14:45 UTC, bitrise-tom commented on roles/go/tests/test_go.py
> +    assert bitrise.user == "linuxbrew"
add a newline

2020-09-01 14:45 UTC, bitrise-tom commented on roles/go/tests/test_go.py
> +def test_go_bin_exists(host):
should we check we have the correct go binary installed?

2020-09-01 14:45 UTC, bitrise-tom commented on roles/remote-access/tests/test_remote_access.py
> +def test_ngrok_exists(host):
test the version? It's actually nice to be warned if it changes

2020-09-01 15:24 UTC, fehersanyi-bitrise commented on roles/go/tests/test_go.py
> +def test_go_bin_exists(host):
how do you imagine that?🧐

2020-09-01 16:07 UTC, bitrise-tom commented on roles/bitrise-cli/tasks/main.yml
> +- name: clean up previous 'bitrise'
why is this resolved?

2020-09-01 16:08 UTC, bitrise-tom commented on roles/bitrise-cli/tasks/main.yml
> +- name: Lookup ansible_distribution
why is this resolved?

2020-09-01 16:08 UTC, bitrise-tom commented on roles/bitrise-cli/tests/test_bitrise_cli.py
> +def test_bitrise_cli_exists(host):
@fehersanyi-bitrise why are you resolving these comments without either fixing or replying?

2020-09-02 06:22 UTC, fehersanyi-bitrise commented on roles/remote-access/tests/test_remote_access.py
> +def test_ngrok_exists(host):
we install the latest stable, I'm not sure if a failing test would be the best way to check if it's updated

2020-09-02 08:09 UTC, fehersanyi-bitrise commented on roles/bitrise-cli/tasks/main.yml
> +- name: clean up previous 'bitrise'
it was removed, I just forget to push it yesterday night

2020-09-02 09:21 UTC, bitrise-tom commented on roles/go/tests/test_go.py
> +def test_go_bin_exists(host):
ok - i see we just brew install the latest. This test will be enough for now

2020-09-02 09:22 UTC, bitrise-tom commented on roles/remote-access/tests/test_remote_access.py
> +def test_ngrok_exists(host):
`/bin.equinox.io/c/gDfFGFRN2Jh/ngrok-link-stable-darwin-amd64.zip`
ngrok comes from a hash URL, so version checking won't be necessary, but can do a similar check to the bitrise clie

```ngrok -v
ngrok version 2.3.34
```

2020-09-02 09:40 UTC, bitrise-tom approved these changes

2020-09-02 09:42 UTC, Kanan-Bitrise approved these changes

2020-09-02 22:01 UTC, peterheja-bitrise approved these changes
lgtm

2020-09-03 07:10 UTC, MrBlaise approved these changes
lgtm

2020-09-03 07:11 UTC, merged