added the tests and the necessary configs
bitrise-io/osx-box-bootstrap pull request #301
Opened 2020-09-07 15:22 UTC by Kanan-Bitrise

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2020-09-11 10:59 UTC, MrBlaise commented on roles/cmd-setup/files/install_brew.sh
> +	echo '' | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
The ruby install is deprecated, consider using this:

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

2020-09-11 11:01 UTC, MrBlaise commented on roles/cmd-setup/tools/cmd-bridge/_scripts/gen_json.rb
> +# puts JSON.dump( JSON.generate(CONFIG_json_content) )
Why are these here commented out? Is this supposed to be example documentation?

2020-09-11 11:05 UTC, Kanan-Bitrise commented on roles/cmd-setup/tools/cmd-bridge/_scripts/gen_json.rb
> +# puts JSON.dump( JSON.generate(CONFIG_json_content) )
Possibly, I haven't written these

2020-09-11 11:05 UTC, fehersanyi-bitrise requested changes

2020-09-11 11:05 UTC, fehersanyi-bitrise commented on playbook.yml
> +    - cmd-setup
This should be `cmd-bridge` I mean the role

2020-09-11 11:05 UTC, fehersanyi-bitrise commented on roles/cmd-setup/files/install_brew.sh
> +#!/bin/bash
you can delete this file as it is

2020-09-11 11:05 UTC, fehersanyi-bitrise commented on roles/cmd-setup/tasks/main.yml
> +---
`Sync the tools/ dir` Should be here as the first step :)

2020-09-11 11:05 UTC, fehersanyi-bitrise commented on roles/misc-setup/files/install_brew.sh
> +#!/bin/bash
delete this file

2020-09-11 11:05 UTC, fehersanyi-bitrise commented on roles/intermediate-setup/tasks/main.yml
>    with_items:
Can you put these folder paths to the defaults.yml file as well please?

2020-09-11 11:05 UTC, Kanan-Bitrise commented on roles/cmd-setup/files/install_brew.sh
> +	echo '' | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
Changed, thanks

2020-09-11 11:05 UTC, MrBlaise commented on roles/intermediate-setup/defaults/main.yml
> +  - name: git-lfs
Is carthage removed intentionally?

2020-09-11 11:07 UTC, MrBlaise requested changes
See my comments

2020-09-11 11:07 UTC, Kanan-Bitrise commented on roles/intermediate-setup/defaults/main.yml
> +  - name: git-lfs
It couldn't be tested due to a brew problem, I moved it to a separate role

2020-09-11 11:09 UTC, MrBlaise commented on roles/cmd-setup/tools/cmd-bridge/_scripts/gen_json.rb
> +# puts JSON.dump( JSON.generate(CONFIG_json_content) )
We should remove commented out code, it can become confusing and we can always find it if required in version control.

2020-09-11 11:50 UTC, fehersanyi-bitrise requested changes
see my comments :)

2020-09-11 11:50 UTC, fehersanyi-bitrise commented on roles/intermediate-setup/files/install_brew.sh
> +	echo '' | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
you can remove this file as well

2020-09-11 11:50 UTC, fehersanyi-bitrise commented on roles/intermediate-setup/tasks/main.yml
>      - { fold_path: 'bitrise/tools' }
so, will you move these out to the defaults.yml as well?

2020-09-11 11:50 UTC, fehersanyi-bitrise commented on roles/intermediate-setup/tasks/main.yml
> +- name: Update the tools folder
this should be in the cmd-bridge role

2020-09-11 12:24 UTC, fehersanyi-bitrise approved these changes
lgtm

2020-09-11 13:57 UTC, fehersanyi-bitrise submitted a review, later dismissed

2020-09-14 06:41 UTC, fehersanyi-bitrise approved these changes

2020-09-14 09:00 UTC, MrBlaise commented on roles/intermediate-setup/tests/test_intermediate_setup.py
> +    assert host.file("/home/linuxbrew/bitrise/tools").exists
You could change this to be similar to `test_brew_packages_exist` (list of strings + for loop). I think that would be a little bit cleaner.

2020-09-14 09:00 UTC, MrBlaise commented on roles/cmd-bridge/tools/cmd-bridge/_scripts/uninstall_launchctl_plist_for_current_user.sh
> +fi
Add a newline at the end here. (I recommend using .editorconfig settings for this)

2020-09-14 09:03 UTC, Kanan-Bitrise commented on roles/intermediate-setup/tests/test_intermediate_setup.py
> +    assert host.file("/home/linuxbrew/bitrise/tools").exists
Yes you're right I forgot to do that cleanup, thanks

2020-09-14 09:12 UTC, MrBlaise submitted a review, later dismissed

2020-09-14 09:14 UTC, MrBlaise submitted a review, later dismissed

2020-09-14 09:16 UTC, bitrise-tom commented on roles/intermediate-setup/defaults/main.yml
> +  - fold_path: git
these would be better in alphabetical order

2020-09-14 09:18 UTC, bitrise-tom requested changes

2020-09-14 09:18 UTC, bitrise-tom commented on roles/intermediate-setup/defaults/main.yml
> +  - name: git
these would be better in alphabetical order

2020-09-14 09:18 UTC, bitrise-tom commented on roles/intermediate-setup/tests/test_intermediate_setup.py
> +    folders = ["/home/linuxbrew/git",
these would be better in alphabetical order

2020-09-14 09:18 UTC, bitrise-tom commented on roles/misc-setup/tasks/main.yml
> +    state: present
Is this version of java pinned via cask?

2020-09-14 09:20 UTC, MrBlaise commented on roles/intermediate-setup/tests/test_intermediate_setup.py
> +    folders = ["/home/linuxbrew/git",
Nitpick: If you are changing this it would also be nicer to add a newline after the opening and before the closing bracket (indent the strings a little). Easier to change and read this way.

2020-09-14 09:31 UTC, fehersanyi-bitrise commented on roles/misc-setup/tasks/main.yml
> +    state: present
it never was in the ansible 🧐

2020-09-14 11:47 UTC, MrBlaise commented on roles/intermediate-setup/tests/test_intermediate_setup.py
> +    "/home/linuxbrew/stepdir"]
One more newline before the closing bracket here, then you can indent the strings a little.

2020-09-14 11:49 UTC, Kanan-Bitrise commented on roles/intermediate-setup/tests/test_intermediate_setup.py
> +    "/home/linuxbrew/stepdir"]
is it good now?

2020-09-14 11:57 UTC, MrBlaise commented on roles/intermediate-setup/tests/test_intermediate_setup.py
> +    "/home/linuxbrew/stepdir"
```suggestion
        "/home/linuxbrew/bin",
        "/home/linuxbrew/bitrise",
        "/home/linuxbrew/bitrise/stepdata",
        "/home/linuxbrew/bitrise/tools",
        "/home/linuxbrew/build",
        "/home/linuxbrew/deploy",
        "/home/linuxbrew/git",
        "/home/linuxbrew/profiles",
        "Library/MobileDevice/Provisioning Profiles",
        "/home/linuxbrew/stepdir"
```

2020-09-14 11:59 UTC, bitrise-tom approved these changes

2020-09-14 12:45 UTC, MrBlaise approved these changes

2020-09-14 12:47 UTC, merged