[IN-1876] ignore xclogparser install in case of 9.4 and 10.3
bitrise-io/osx-box-bootstrap pull request #311
Opened 2020-09-17 07:02 UTC by lmesz-bitrise

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2020-09-17 07:03 UTC, fehersanyi-bitrise approved these changes
lgtm

2020-09-17 07:10 UTC, MrBlaise commented on roles/weekly-update-shared/tasks/main.yml
> +  when: xcode_version.stdout != "Xcode 9.4" || xcode_version.stdout != "Xcode 10.3"
This should be an *and* (&&) instead of an *or* (||)

2020-09-17 07:10 UTC, lmesz-bitrise commented on roles/weekly-update-shared/tasks/main.yml
> +  when: xcode_version.stdout != "Xcode 9.4" || xcode_version.stdout != "Xcode 10.3"
?

2020-09-17 07:17 UTC, MrBlaise submitted a review, later dismissed

2020-09-20 21:30 UTC, peterheja-bitrise submitted a review, later dismissed
LGTM

2020-09-21 12:00 UTC, peterheja-bitrise approved these changes
LGTM

2020-09-21 12:16 UTC, MrBlaise approved these changes

2020-09-21 12:17 UTC, fehersanyi-bitrise approved these changes

2020-09-21 12:22 UTC, MrBlaise approved these changes

2020-09-21 12:24 UTC, peterheja-bitrise approved these changes
lgtm

2020-09-21 21:57 UTC, peterheja-bitrise requested changes
explain `&& v`

2020-09-21 22:04 UTC, lmesz-bitrise commented
> explain `&& v`

Ohh sometimes I mark my changes with that symbol :) /sarcasm
Nice catch, Sorry I left it there accidentally. :)

2020-09-22 07:26 UTC, MrBlaise approved these changes

2020-09-22 12:49 UTC, peterheja-bitrise approved these changes
LGTM

2021-02-02 09:07 UTC, closed without merging