Add certs ansible
bitrise-io/osx-box-bootstrap pull request #314
Opened 2020-09-24 08:17 UTC by bitrisekristof

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2020-09-24 08:19 UTC, peterheja-bitrise requested changes
We should try to make our desired state idempotent - so there is no change if we run it twice.

2020-09-24 08:19 UTC, peterheja-bitrise commented on roles/certs/tasks/main.yml
> +  shell: bash -l -c "curl https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer --output apple_cert.cer"
Add absolute path for this, and a conditional, so it does not run always.

2020-09-24 08:19 UTC, peterheja-bitrise commented on roles/certs/tasks/main.yml
> +  shell: bash -l -c "sudo security add-certificates -k /Library/Keychains/System.keychain apple_cert.cer"
Absolute path, and conditional, so it does not always run.

2020-09-25 12:27 UTC, MrBlaise commented on bitrise.yml
> +            sudo pip3 install ansible-lint
If you don't pin the linter version it can break after a while. Might be good idea to keep the version pinning.

2020-09-28 08:20 UTC, fehersanyi-bitrise approved these changes

2020-09-28 08:25 UTC, MrBlaise approved these changes

2020-09-28 08:30 UTC, MrBlaise requested changes

2020-09-28 08:30 UTC, MrBlaise commented on roles/certs/tasks/main.yml
> +  shell: bash -l -c "sudo security add-certificates -k /Library/Keychains/System.keychain $HOME/apple_cert.cer"
You could register the output of the get_url task and only run this shell command when that has changed using when. This way the command doesn't always run.

2020-09-28 09:08 UTC, fehersanyi-bitrise commented on roles/certs/tasks/main.yml
> +  shell: bash -l -c "sudo security add-certificates -k /Library/Keychains/System.keychain $HOME/apple_cert.cer"
But there will be no case when it is there, it will always have to run.

2020-09-28 09:13 UTC, MrBlaise commented on roles/certs/tasks/main.yml
> +  shell: bash -l -c "sudo security add-certificates -k /Library/Keychains/System.keychain $HOME/apple_cert.cer"
We talked offline

tldr: this is always running on a fresh vm and on failure it is recreated from scratch so I can accept this

2020-09-28 09:13 UTC, MrBlaise approved these changes

2020-09-28 09:18 UTC, peterheja-bitrise commented on roles/certs/tasks/main.yml
> +  shell: bash -l -c "sudo security add-certificates -k /Library/Keychains/System.keychain $HOME/apple_cert.cer"
If we ever want to do local development in the near future, then we should do idempotent roles when we are writing them, not later.
That also means we wouldn't be always running against fresh VMs, and also it is nice to describe a desired state, not just series of commands.

What was the problem with the earlier state of this PR?

2020-09-28 09:20 UTC, fehersanyi-bitrise commented on roles/certs/tasks/main.yml
> +  shell: bash -l -c "sudo security add-certificates -k /Library/Keychains/System.keychain $HOME/apple_cert.cer"
it didn't work 🤷‍♂️
also at the current time, this is an absolutely valid state. we don't do local testing, nor local environment. but this certificate NEEDS to be on the machines that use Xcode 12 or later.

2020-09-28 09:23 UTC, peterheja-bitrise approved these changes
.

2020-09-28 09:23 UTC, peterheja-bitrise commented on roles/certs/tasks/main.yml
> +  shell: bash -l -c "sudo security add-certificates -k /Library/Keychains/System.keychain $HOME/apple_cert.cer"
Then let's accept this as tech dept for later.
Approved PR, so it can be merged.

2020-09-28 09:24 UTC, merged