[IN-1977] enable accessibility for xcode, need some explanation will ad…
bitrise-io/osx-box-bootstrap pull request #317
Opened 2020-09-24 16:05 UTC by lmesz-bitrise

…d later

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2020-11-04 09:30 UTC, bitrise-tom commented on roles/install-xcode/tasks/main.yml
> +
can we add a condition here for this to be for 10.15.6? I don't want this to do odd things when big sur comes along

2020-11-04 09:31 UTC, lmesz-bitrise commented on roles/install-xcode/tasks/main.yml
> +
I agree. Is it okay to fail if the os is not 10.15.6?

2020-11-04 09:35 UTC, bitrise-tom commented on roles/install-xcode/tasks/main.yml
> +
failing is a good idea, so we fix it

2020-11-25 13:18 UTC, peterheja-bitrise commented on roles/install-xcode/tasks/main.yml
> +
+1

2020-11-25 13:19 UTC, peterheja-bitrise requested changes
Do the big sur fail change

2020-11-25 13:19 UTC, lmesz-bitrise commented on roles/install-xcode/tasks/main.yml
> +
Ahhh I totally forget that PR. Let me fix the PR and merge.

2020-12-02 12:57 UTC, lmesz-bitrise commented on roles/install-xcode/tasks/main.yml
> +
Failure added

2020-12-02 13:07 UTC, fehersanyi-bitrise approved these changes

2020-12-03 08:46 UTC, MrBlaise commented on roles/install-xcode/tasks/main.yml
> +# TODO: We should use profiles for enable accessibility but it needs more time and investigation, will happen in the upcoming sprint
Is this comment still true?

2020-12-03 08:46 UTC, MrBlaise commented on roles/install-xcode/tasks/main.yml
> +# TODO: We should use profiles for enable accessibility but it needs more time and investigation, will happen in the upcoming sprint
Nevermind I see it in slack.

2020-12-03 08:46 UTC, fehersanyi-bitrise commented on roles/install-xcode/tasks/main.yml
> +# TODO: We should use profiles for enable accessibility but it needs more time and investigation, will happen in the upcoming sprint
this is the truest of them all, we should do it via a plist file but we couldn't figure it out yet

2020-12-03 08:48 UTC, MrBlaise commented on roles/install-xcode/tasks/main.yml
> +- name: Fail if we are not on Catalina
Shouldn't we fail before the enable accessibility task?

2020-12-03 08:56 UTC, lmesz-bitrise commented on roles/install-xcode/tasks/main.yml
> +- name: Fail if we are not on Catalina
True, install take a while, moved upward.

2020-12-03 08:58 UTC, fehersanyi-bitrise submitted a review, later dismissed

2020-12-03 08:59 UTC, MrBlaise approved these changes

2020-12-03 09:23 UTC, MrBlaise approved these changes

2020-12-03 09:33 UTC, peterheja-bitrise approved these changes

2020-12-03 10:45 UTC, merged