[IN-1721] Use virtualenv + requirements.txt for molecule
bitrise-io/osx-box-bootstrap pull request #330
Opened 2020-10-07 13:00 UTC by MrBlaise

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2020-10-07 14:10 UTC, bitrise-tom requested changes

2020-10-07 14:10 UTC, bitrise-tom commented on _scripts/molecule/molecule_requirements.txt
> +# pip3 install molecule testinfra docker pytest && pip freeze > molecule_requirements.txt
this shouldn't be here

Also, this file should just be called requirements.txt - it s already in the molecule directory

2020-10-07 14:11 UTC, MrBlaise commented on _scripts/molecule/molecule_requirements.txt
> +# pip3 install molecule testinfra docker pytest && pip freeze > molecule_requirements.txt
Should I create a README here? The comment was just to show how this file can be created. I will rename the requirements

2020-10-07 14:14 UTC, MrBlaise commented on _scripts/molecule/molecule_requirements.txt
> +# pip3 install molecule testinfra docker pytest && pip freeze > molecule_requirements.txt
Created a readme and renamed the files

2020-10-07 14:28 UTC, lmesz-bitrise commented on _scripts/molecule/install_dependencies.sh
> +mkdir -p ~/.venv/
It is not necessary.

2020-10-07 14:28 UTC, lmesz-bitrise commented on _scripts/molecule/install_dependencies.sh
> +echo "Successfully installed $molecule_version"
I am pretty sure we will realize if it fails since set -e.

2020-10-07 14:28 UTC, lmesz-bitrise commented on _scripts/molecule/install_dependencies.sh
> +python3 -m venv ~/.venv/molecule
Why not just a simple `virtualenv molecule`? Is there a specific reason for the directory structure?

2020-10-07 15:00 UTC, MrBlaise commented on _scripts/molecule/install_dependencies.sh
> +echo "Successfully installed $molecule_version"
What is this regarding? The echo message? It was already there I just did not remove it.

2020-10-07 15:00 UTC, MrBlaise commented on _scripts/molecule/install_dependencies.sh
> +mkdir -p ~/.venv/
Why? This way if venv already exists it won't fail.

2020-10-07 15:01 UTC, MrBlaise commented on _scripts/molecule/install_dependencies.sh
> +python3 -m venv ~/.venv/molecule
If you mean why ~/.venv/molecule, then the reason is that it is in a familiar place even when you run it locally. Doesn't matter too much but it must be somewhere and the home directory looks like a good place.

2020-10-07 15:03 UTC, lmesz-bitrise commented on _scripts/molecule/install_dependencies.sh
> +mkdir -p ~/.venv/
The whole mkdir not necessary, not just the -p. `virtualenv csillamponi/csillamponi` works as well.

2020-10-07 15:04 UTC, lmesz-bitrise commented on _scripts/molecule/install_dependencies.sh
> +echo "Successfully installed $molecule_version"
Ohh okay.

2020-10-07 15:05 UTC, lmesz-bitrise commented on _scripts/molecule/install_dependencies.sh
> +python3 -m venv ~/.venv/molecule
I am okay with it. Just didn't know why it must be a hidden directory and why it needs a second level.

2020-10-08 07:14 UTC, MrBlaise commented on _scripts/molecule/install_dependencies.sh
> +mkdir -p ~/.venv/
I see, I'll fix this

2020-10-08 10:32 UTC, bitrise-tom approved these changes

2020-10-09 08:02 UTC, peterheja-bitrise commented on _scripts/molecule/install_dependencies.sh
> +python3 -m venv ~/.venv/molecule
`mkdir -p ~/.venv/`

2020-10-09 08:06 UTC, peterheja-bitrise commented on _scripts/molecule/install_dependencies.sh
> +python3 -m venv ~/.venv/molecule
@MrBlaise has educated me, that this creates parent dirs.
TIL. :)
```shell
> python3 -m venv /tmp/this/does/not/exist/for/sure/.venv
> ls -lhsa /tmp/this/does/not/exist/for/sure/.venv
total 8
0 drwxr-xr-x   6 peterheja  wheel   192B Oct  9 10:05 .
0 drwxr-xr-x   3 peterheja  wheel    96B Oct  9 10:05 ..
0 drwxr-xr-x  13 peterheja  wheel   416B Oct  9 10:05 bin
0 drwxr-xr-x   2 peterheja  wheel    64B Oct  9 10:05 include
0 drwxr-xr-x   3 peterheja  wheel    96B Oct  9 10:05 lib
8 -rw-r--r--   1 peterheja  wheel    75B Oct  9 10:05 pyvenv.cfg
```

2020-10-09 08:06 UTC, peterheja-bitrise approved these changes
LGTM

2020-10-09 08:39 UTC, merged