[IN-2117] disable homebrew install cleanup
bitrise-io/osx-box-bootstrap pull request #337
Opened 2020-11-03 08:39 UTC by Kanan-Bitrise

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [x] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [x] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2020-11-03 08:41 UTC, lmesz-bitrise submitted a review, later dismissed

2020-11-03 08:41 UTC, MrBlaise approved these changes

2020-11-03 08:55 UTC, bitrise-tom requested changes
As part of this PR, shouldn't we be running the cleanup as part of the build, then disabling on the end VMs?

2020-11-03 09:00 UTC, Kanan-Bitrise commented
I wasn't aware of that, thanks!

2020-11-03 10:36 UTC, lmesz-bitrise requested changes

2020-11-03 10:36 UTC, lmesz-bitrise commented on roles/profiles/files/bashrc
> +# Don't do install cleanup
I would rephrase it to something like "Do not do execute brew cleanup during install" or simply remove it cause the variable talks itself

2020-11-03 10:36 UTC, lmesz-bitrise commented on CHANGELOG.md
> +* `disable homebrew install cleanup`
I would rephrase it also

2020-11-03 10:36 UTC, lmesz-bitrise commented on roles/weekly-update-shared/tasks/main.yml
> +    tasks_from: main
This is the default don't need to add it.

2020-11-03 10:36 UTC, lmesz-bitrise commented on roles/brew-cleanup-weekly/tasks/main.yml
> +- name: Brew cleanup weekly
Hm... are you sure it will work like this? I think brew is installed under `/usr/local/bin` which is not part of the PATH

2020-11-03 10:42 UTC, lmesz-bitrise commented
Why did you just resolve the comments without any reaction?

2020-11-03 10:49 UTC, Kanan-Bitrise commented
oh sorry forgot to push

2020-11-04 09:10 UTC, bitrise-tom requested changes

2020-11-04 09:10 UTC, bitrise-tom commented on roles/profiles/files/bashrc
> +export HOMEBREW_NO_INSTALL_CLEANUP=1
remove the space above this and keep the env vars for homebrew together

2020-11-04 09:10 UTC, bitrise-tom commented on roles/profiles/files/zshrc
> +export HOMEBREW_NO_INSTALL_CLEANUP=1
unnecessary space

2020-11-04 09:28 UTC, bitrise-tom approved these changes

2020-11-04 09:42 UTC, lmesz-bitrise approved these changes

2020-11-04 10:48 UTC, merged