[IN-2227] Permission fix + remove hardcoded ids and simulators
bitrise-io/osx-box-bootstrap pull request #346
Opened 2020-11-30 11:30 UTC by MrBlaise

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2020-11-30 14:10 UTC, MrBlaise commented
This is blocked until this PR is merged or solved here: https://github.com/bitrise-io/osx-box-bootstrap/pull/317

2020-11-30 14:25 UTC, bitrise-tom commented on roles/install-xcode/tasks/main.yml
> +# this task is here to make sure it is executed at least once before we are trying to read its output
On this principle, why not just have an ansible `retry: 2` on the next task?

2020-11-30 14:32 UTC, MrBlaise commented on roles/install-xcode/tasks/main.yml
> +# this task is here to make sure it is executed at least once before we are trying to read its output
You are right, with pipefail it should be good.

2020-11-30 16:36 UTC, bitrise-tom submitted a review, later dismissed
looks nice

2020-12-03 12:08 UTC, lmesz-bitrise requested changes

2020-12-03 12:08 UTC, lmesz-bitrise commented on roles/install-xcode/tasks/main.yml
> +  register: ios_simulator
What is the reason for the tries?

2020-12-03 12:08 UTC, lmesz-bitrise commented on roles/install-xcode/tasks/main.yml
> +  shell: bash -l -c "sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = {{ ios_simulator.stdout.split()[0] }};/g' /opt/bitrise/testapps/bitrise/bitrise.xcodeproj/project.pbxpr
Please use template instead of sed.

2020-12-03 12:09 UTC, MrBlaise commented on roles/install-xcode/files/get_latest_simulator.py
> +lines = [line for line in lines if "Watch" not in line and "iPhone SE" not in line and line]
I think it is clearer this way since I am already using python, I wanted the bash command to be minimal

2020-12-03 12:11 UTC, MrBlaise commented on roles/install-xcode/tasks/main.yml
> +  register: ios_simulator
It was previously commented here, the comment has since been removed. Sometimes xcrun xctrace list devices won't give back the device list on the first run. (Based on the experience doing this manually), hence the retry to make sure we can recover in such cases and continue the automation.

2020-12-03 12:12 UTC, MrBlaise commented on roles/install-xcode/tasks/main.yml
> +  shell: bash -l -c "sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = {{ ios_simulator.stdout.split()[0] }};/g' /opt/bitrise/testapps/bitrise/bitrise.xcodeproj/project.pbxpr
What do you mean? How would that look like? The files are downloaded from the git repo, I am using sed here to change it to the current latest simulator.

2020-12-03 12:15 UTC, MrBlaise commented on roles/install-xcode/tasks/main.yml
> +  register: ios_simulator
Added the comment.

2020-12-03 12:39 UTC, lmesz-bitrise commented on roles/install-xcode/files/get_latest_simulator.py
> +lines = [line for line in lines if "Watch" not in line and "iPhone SE" not in line and line]
I feel a little ambiguous here. You do the filtering at two places. First, you filter for iPhone with grep and filtering with list comprehension. It would be better to be consistent and do the filtering at one place.

2020-12-03 12:42 UTC, lmesz-bitrise commented on roles/install-xcode/tasks/main.yml
> +  shell: bash -l -c "sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = {{ ios_simulator.stdout.split()[0] }};/g' /opt/bitrise/testapps/bitrise/bitrise.xcodeproj/project.pbxpr
it is in a git repo that maintained by us. So either I would put the template in the original repo or the file should be stored here in the template directory and override the file a with ansible.

2020-12-03 12:45 UTC, MrBlaise commented on roles/install-xcode/tasks/main.yml
> +  shell: bash -l -c "sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = {{ ios_simulator.stdout.split()[0] }};/g' /opt/bitrise/testapps/bitrise/bitrise.xcodeproj/project.pbxpr
But then I would have to have the whole file here with all of its content only to change these lines right? I feel this is a better solution at the moment (we talked about doing a properly generated project for each stack later which will solve this as well). This is straightforward and if something changes in the sample app repo this will still work.

2020-12-03 12:48 UTC, MrBlaise commented on roles/install-xcode/files/get_latest_simulator.py
> +lines = [line for line in lines if "Watch" not in line and "iPhone SE" not in line and line]
I moved the filtering to bash then.

2020-12-03 12:49 UTC, lmesz-bitrise commented on roles/install-xcode/tasks/main.yml
> +  shell: bash -l -c "sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = {{ ios_simulator.stdout.split()[0] }};/g' /opt/bitrise/testapps/bitrise/bitrise.xcodeproj/project.pbxpr
I partially agree with the "if something changes in the sample app repo this will still work" they don't need to change much to break it. But yeah generation is the way to go. So alright fine for now.

2020-12-03 12:54 UTC, lmesz-bitrise approved these changes

2020-12-03 14:40 UTC, peterheja-bitrise approved these changes
LGTM

2020-12-04 08:36 UTC, merged