[IN-2442] use ansible builtins to mirror own git repo
bitrise-io/osx-box-bootstrap pull request #384
Opened 2021-02-10 14:54 UTC by bitrise-tom

- [IN-2442] homebrew install javas with cask option
- [IN-2442] use ansible builtins to mirror own git repo

** This should eventually move into the Brew role **
this is a stage 1 exit to use ansible's built in modules
to configure the local mirror of brew cask-versions

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2021-02-10 14:55 UTC, peterheja-bitrise requested changes
Drop commit b47697a42f07845645ce00b08cddd4e96c742848

2021-02-10 14:55 UTC, peterheja-bitrise commented on roles/java/tasks/main.yml
> +    install_options: cask
b47697a42f07845645ce00b08cddd4e96c742848

2021-02-10 14:55 UTC, peterheja-bitrise commented on roles/java/tasks/main.yml
> +    install_options: cask
b47697a42f07845645ce00b08cddd4e96c742848

2021-02-10 14:56 UTC, bitrise-tom commented on roles/java/tasks/main.yml
> +    install_options: cask
when i merge the first PR, these will vanish :)

2021-02-10 14:56 UTC, bitrise-tom commented on roles/java/tasks/main.yml
> +    install_options: cask
when i merge the first PR, these will vanish :)

2021-02-10 15:04 UTC, fehersanyi-bitrise submitted a review, later dismissed

2021-02-10 16:01 UTC, fehersanyi-bitrise approved these changes

2021-02-11 07:34 UTC, peterheja-bitrise approved these changes
LGTM

2021-02-11 09:31 UTC, merged