[IN-2468] Hardcode Xclogparser to 0.2.21 so we can install it on all relevant VMs
bitrise-io/osx-box-bootstrap pull request #390
Opened 2021-02-16 13:03 UTC by fehersanyi-bitrise

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2021-02-16 14:30 UTC, bitrise-tom requested changes
Two questions.
1. How do you know that v 0.2.21 is installed?
2. what happens to `which` when `/usr/local/bin` isn't in the path (i know it __should__ be)

2021-02-16 14:49 UTC, fehersanyi-bitrise commented
@bitrise-tom it is the first item added to PATH in the profiles
https://github.com/bitrise-io/osx-box-bootstrap/blob/104d08ac7f15dd36316a073c368906eb2eeaa415/roles/profiles/files/zshrc#L1

2021-02-16 14:50 UTC, fehersanyi-bitrise commented
@bitrise-tom 
1. it shouldn't be installed at all when this role is run. the check is only there for idempotency 🤷‍♂️

2021-02-16 14:56 UTC, bitrise-tom commented
this is the weekly 

> @bitrise-tom
> 
> 1. it shouldn't be installed at all when this role is run. the check is only there for idempotency man_shrugging

this is the weekly update cache role, so it's going to run every week

The idempotency isn't really working as if you update the version number for a new release, it won't even download if there is any file already there

2021-02-16 14:58 UTC, fehersanyi-bitrise commented
@bitrise-tom then what do you recommend? 
maybe checking the version, and if there is none or it is not the version we want, then we install it? 🧐

2021-02-16 15:08 UTC, peterheja-bitrise requested changes
First of all: are we sure we want to hardcode `xclogparser` to a fixed version across all stacks? I'm not against it, but it might be troublesome to update it.
Although, in the long run this is definitely something I support!
(So, it is +1 from me, but we have to be careful around this - it might rot!)

Secondly, there are some issues:
Does not take into account if `xclogparser` is older, than what we want
We should check for the output to include the version we want.

Does not hardcode / check for checksum.
We should have on the get_url the checksum parameter
We can get it by
```shasum -a 256 XCLogParser-macOS-x86_64-v0.2.21.zip
f74caec7c8710dcdb0f4089001fd62d14daa5d3922b9b69626d7b9ce7b8e33e9  XCLogParser-macOS-x86_64-v0.2.21.zip```

2021-02-16 15:08 UTC, peterheja-bitrise commented on roles/weekly-update-shared/tasks/main.yml
> +    url: https://github.com/spotify/XCLogParser/releases/download/v0.2.21/XCLogParser-macOS-x86_64-v0.2.21.zip
```suggestion
    url: https://github.com/spotify/XCLogParser/releases/download/v0.2.21/XCLogParser-macOS-x86_64-v0.2.21.zip
    checksum: sha256:f74caec7c8710dcdb0f4089001fd62d14daa5d3922b9b69626d7b9ce7b8e33e9
```

2021-02-16 15:09 UTC, peterheja-bitrise commented on roles/weekly-update-shared/tasks/main.yml
> +- name: Check if Xclogparser is present
This should register / check the version

2021-02-16 15:13 UTC, peterheja-bitrise commented on roles/weekly-update-shared/tasks/main.yml
> +    dest: /tmp/xclogpraser.zip
`xclogpraser` not `xclogparser`

2021-02-16 15:14 UTC, peterheja-bitrise commented on roles/weekly-update-shared/tasks/main.yml
> +- name: unarchive xclogpraser binary
`xclogpraser` not `xclogparser`

2021-02-16 15:14 UTC, peterheja-bitrise commented on roles/weekly-update-shared/tasks/main.yml
> +    src: /tmp/xclogpraser.zip
`xclogpraser` not `xclogparser`

2021-02-16 15:44 UTC, fehersanyi-bitrise commented
@peterheja-bitrise in my opinion this is the safest way to go at the moment, I would not introduce any questionable logic into the system, with extra maintenance cost. I don't think I need to give reasoning to why I think this.

2021-02-16 15:52 UTC, peterheja-bitrise approved these changes

2021-02-16 15:56 UTC, peterheja-bitrise requested changes
Use full paths

2021-02-16 15:56 UTC, peterheja-bitrise commented on roles/weekly-update-shared/tasks/main.yml
> +  shell: xclogparser version | awk '{print $2}'
Use full path

2021-02-16 17:16 UTC, bitrise-tom commented on roles/weekly-update-shared/tasks/main.yml
> +    dest: /usr/local/bin/xclogparser
Is this correct?
I think this will unpack the binary to `/usr/local/bin/xclogparser/xclogparser`

2021-02-17 09:07 UTC, fehersanyi-bitrise commented on roles/weekly-update-shared/tasks/main.yml
> +    dest: /usr/local/bin/xclogparser
you are right

2021-02-17 09:15 UTC, peterheja-bitrise submitted a review, later dismissed
LGTM

2021-02-17 09:24 UTC, bitrise-tom requested changes

2021-02-17 09:24 UTC, bitrise-tom commented on roles/weekly-update-shared/tasks/main.yml
> +  when: xclogparser_is_present.rc != 0 or xclogparser_is_present != 0.2.21
this conditional should be based on  `xclogparser_is_present.stdout`  to match the version number

2021-02-17 09:24 UTC, bitrise-tom commented on roles/weekly-update-shared/tasks/main.yml
> +  when: xclogparser_is_present.rc != 0 or xclogparser_is_present != 0.2.21
this conditional should be based on  `xclogparser_is_present.stdout`  to match the version number

2021-02-17 09:33 UTC, peterheja-bitrise approved these changes
LGTM

2021-02-17 09:35 UTC, bitrise-tom commented on roles/weekly-update-shared/tasks/main.yml
> +  when: xclogparser_is_present.rc != 0 or xclogparser_is_present.stdout != 0.2.21
I think you will need to quote the "0.2.21"

2021-02-17 12:16 UTC, peterheja-bitrise approved these changes
LGTM

2021-02-17 12:21 UTC, bitrise-tom approved these changes

2021-02-17 13:22 UTC, merged