[IN-2481] Add java 11 to jenv
bitrise-io/osx-box-bootstrap pull request #392
Opened 2021-02-17 09:43 UTC by fehersanyi-bitrise

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2021-02-17 12:17 UTC, peterheja-bitrise approved these changes
I like the intent, but I'm unsure about Line18-19 in jenv/tasks/main.yml

2021-02-17 12:24 UTC, bitrise-tom commented on roles/java/tasks/main.yml
> +  register: detect_java_8_home
i don't see why these need registering

I know it was here before, but why are we ignoring errors?

2021-02-17 12:34 UTC, fehersanyi-bitrise commented on roles/java/tasks/main.yml
> +  register: detect_java_8_home
the registering is needed for jenv so we can set it up ready to be used

2021-02-17 12:35 UTC, fehersanyi-bitrise commented
@peterheja-bitrise line 18-19 is required so we can set up java 8 as default with jenv

2021-02-18 10:34 UTC, bitrise-tom requested changes
please add a metadata file to jenv role to fix the dependency

2021-02-18 15:40 UTC, peterheja-bitrise requested changes

2021-02-18 15:40 UTC, peterheja-bitrise commented on CHANGELOG.md
> +* `Add Java 11 to jenv`
Should be v2021_02_18_2

2021-02-18 15:40 UTC, peterheja-bitrise commented on roles/profiles/files/bitrise_profile
> +export BITRISE_OSX_STACK_REV_ID=v2021_02_18-2
Should be v2021_02_18_2

2021-02-18 15:57 UTC, fehersanyi-bitrise commented on CHANGELOG.md
> +* `Add Java 11 to jenv`
nah, it was the first change made today. also there is already a _3 somewhere. should this be _4 then?

2021-02-18 15:58 UTC, fehersanyi-bitrise commented on CHANGELOG.md
> +* `Add Java 11 to jenv`
the change log can go under the same date IMO. on the 18th of february, we made these changes

2021-02-18 16:00 UTC, fehersanyi-bitrise commented on CHANGELOG.md
> +* `Add Java 11 to jenv`
but I changed it regardless

2021-02-18 16:02 UTC, peterheja-bitrise commented on CHANGELOG.md
> +* `Add Java 11 to jenv`
This is just so we can have exact changes referenced in profile, because if we have in the repo another change under the same profile number, then the users might be tricked into thinking they are running with one version, not the other.

2021-02-18 16:13 UTC, peterheja-bitrise approved these changes
LGTM

2021-02-18 16:25 UTC, bitrise-tom approved these changes

2021-02-18 16:25 UTC, merged