[IN-2473] (xcode) debug logs and robust xcode selection
bitrise-io/osx-box-bootstrap pull request #436
Opened 2021-03-18 16:14 UTC by bitrise-tom

- [IN-2473] (xcode) debug logs and robust xcode selection
- metadatas

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

I have added some debug loggin so we can see in the Ansible output what version and build ID Xcode is installed
I took the opportunity to make better use of xcversion and xcode-select to ensure the environment is setup
correctly for developers

2021-03-18 16:54 UTC, nagypeterjob submitted a review, later dismissed

2021-03-19 09:27 UTC, fehersanyi-bitrise requested changes
at this point, I would put a check in the beggining, to see if we already have an Xcode installed or not, and if it's the same version we want. if true, then skip the thing, if not then clean up and reinstall. this could come handy with beta stacks or something

2021-03-19 09:27 UTC, fehersanyi-bitrise commented on roles/xcode/tasks/main.yml
>    shell: bash -l -c "$HOME/.rbenv/shims/xcversion install '{{ xcode_version }}'"
So I learned this cool thing last week
```suggestion
  shell: xcversion install '{{ xcode_version }}'
  args:
    executable: "$HOME/.rbenv/shims/xcversion"
```

2021-03-19 09:27 UTC, fehersanyi-bitrise commented on roles/xcode/tasks/main.yml
> +- name: Display the installed xcoder versions
xcode, not xcoder

2021-03-19 09:27 UTC, fehersanyi-bitrise commented on roles/xcode/tasks/main.yml
> +  shell: bash -l -c "xcversion selected; xcode-select -p"
are you sure this is fine? it has 3 lines in stdout as follows:
```
Xcode 12.4
Build version 12D4e
/Applications/Xcode.app/Contents/Developer
```
this is an exxample

2021-03-19 09:27 UTC, fehersanyi-bitrise commented on roles/xcode/tasks/main.yml
>    shell: bash -l -c "$HOME/.rbenv/shims/xcversion install '{{ xcode_version }}'"
or it can be
```
shell: "$HOME/.rbenv/shims/xcversion install '{{ xcode_version }}'"
  args:
    executable: /bin/bash
```

2021-03-19 11:12 UTC, bitrise-tom commented on roles/xcode/tasks/main.yml
> +  shell: bash -l -c "xcversion selected; xcode-select -p"
Yes, this is a debug line that i think is useful to have in the logs

The build version is especially useful when doing beta Xcodes, so that we can compare the hash to the rss feed

2021-03-29 08:41 UTC, bitrise-tom commented on roles/xcode/tasks/main.yml
>    shell: bash -l -c "$HOME/.rbenv/shims/xcversion install '{{ xcode_version }}'"
we know why this doesn't work :)

2021-03-29 08:42 UTC, fehersanyi-bitrise requested changes

2021-03-29 08:42 UTC, fehersanyi-bitrise commented on roles/xcode/tasks/main.yml
> +  shell: bash -l -c "$HOME/.rbenv/shims/xcversion selected | grep Xcode | grep {{ xcode_version.split(' ')[0] }}"
change HOME to {{ ansible_env.HOME }}

2021-03-29 08:43 UTC, fehersanyi-bitrise commented on roles/xcode/tasks/main.yml
>    shell: bash -l -c "$HOME/.rbenv/shims/xcversion install '{{ xcode_version }}'"
yes, now we know

2021-03-29 09:05 UTC, nagypeterjob commented on roles/profiles/files/bitrise_profile
> +<<<<<<< HEAD
oops

2021-03-29 09:09 UTC, fehersanyi-bitrise submitted a review, later dismissed

2021-03-29 09:11 UTC, nagypeterjob approved these changes

2021-03-29 09:11 UTC, nagypeterjob commented on roles/xcode/tasks/main.yml
> +name: Install xcode '{{ xcode_version }}', it could take a while. About an hour, so be patient.
If you meant to interpolate `xcode_version` it probably won't work here. If it is just documentation, then its ok.

2021-03-29 09:21 UTC, peterheja-bitrise requested changes

2021-03-29 09:21 UTC, peterheja-bitrise commented on roles/xcode/files/enable_accessibility.sh
> +elif test "z$1" = "z11.2" || test "z$1" = "z11.2.3" ; then
Unrelated change

2021-03-29 09:27 UTC, bitrise-tom commented on roles/xcode/files/enable_accessibility.sh
> +elif test "z$1" = "z11.2" || test "z$1" = "z11.2.3" ; then
It's part of the same changeset to get 12.5 installing on Big sure layers

2021-03-29 10:39 UTC, peterheja-bitrise commented on roles/xcode/files/enable_accessibility.sh
> +elif test "z$1" = "z11.2" || test "z$1" = "z11.2.3" ; then
Tbh. we should switch to something that we don't have to expand every time (I know, this is a good safeguard, but I don't think it will break in x.y.* versions):
```if echo "${1}" | grep -e "^11\.2\."```

2021-03-29 10:57 UTC, bitrise-tom commented on roles/xcode/files/enable_accessibility.sh
> +elif test "z$1" = "z11.2" || test "z$1" = "z11.2.3" ; then
yeah, I know.
let me try something

2021-03-29 13:24 UTC, bitrise-tom commented on roles/xcode/tasks/main.yml
> +name: Install xcode '{{ xcode_version }}', it could take a while. About an hour, so be patient.
It displays quite nicely the version, which is useful when debugging

2021-03-29 13:33 UTC, nagypeterjob commented on roles/xcode/tasks/main.yml
> +name: Install xcode '{{ xcode_version }}', it could take a while. About an hour, so be patient.
Oh. I had the notion that variables won't get rendered inside task names. Maybe my knowledge was outdated. Then it is good to go on my side.

2021-03-29 13:43 UTC, peterheja-bitrise commented on roles/xcode/files/enable_accessibility.sh
> +if test "z$OS_MAJOR_VERSION" = z10; then
This is 15 years of releases, the "major" is not enough, we need minor as well.

2021-03-29 13:45 UTC, peterheja-bitrise commented on roles/xcode/tasks/main.yml
> +  register: xcode_select_selected
Rather `xcode_select_output` or `xcode_select_current` or `..._current_selection`, because this is just a confusing variable name.

2021-03-29 13:45 UTC, peterheja-bitrise commented on roles/xcode/tasks/main.yml
> +  shell: bash -l -c "xcode-select -p | grep {{ xcode_version.split(' ')[0] }}"
Please, add some comments or something, because this is uneasy on the eyes

2021-03-29 13:46 UTC, peterheja-bitrise commented on roles/xcode/tasks/main.yml
> +- name: Get the installed Xcode version
Maybe get this into a block, so it is easier to see this is a debug block?

2021-03-29 13:47 UTC, peterheja-bitrise commented on roles/xcode/tasks/main.yml
> +  shell: bash -l -c "/usr/bin/xcode-select --switch /Applications/Xcode-{{ xcode_version|replace(' ','.')}}.app"
Please, add some comments or something, because this is uneasy on the eyes

2021-03-29 13:48 UTC, peterheja-bitrise commented on roles/xcode/tasks/main.yml
> +  when: xcode_select_selected.rc != 0
I'd much rather have some nice string matching here, would be way more explicit

2021-03-29 13:49 UTC, peterheja-bitrise commented on roles/xcode/tasks/main.yml
> +  shell: bash -l -c "{{ ansible_env.HOME }}/.rbenv/shims/xcversion selected | grep Xcode | grep {{ xcode_version.split(' ')[0] }}"
This is in `PATH` after sourcing `.bashrc`, please do that instead.
Also, make sure all other `xcversion` calls are made the same way, e.g. here https://github.com/bitrise-io/osx-box-bootstrap/pull/436/files#diff-8917591fa6bf75bb617a67ff94022ce14f390f04202674a0a465ce467397f262R16

2021-03-29 13:49 UTC, peterheja-bitrise commented on roles/xcode/tasks/main.yml
> +  shell: bash -l -c "{{ ansible_env.HOME }}/.rbenv/shims/xcversion select {{ xcode_version.split(' ')[0] }}"
Same as above.

2021-03-29 13:49 UTC, peterheja-bitrise commented on roles/xcode/tasks/main.yml
> +  shell: bash -l -c "{{ ansible_env.HOME }}/.rbenv/shims/xcversion cleanup"
Same as above

2021-03-29 13:50 UTC, peterheja-bitrise commented on roles/xcode/tasks/main.yml
> +  script: enable_accessibility.sh '{{ ansible_distribution_version }}'
Why?

2021-03-29 13:53 UTC, bitrise-tom commented on roles/xcode/files/enable_accessibility.sh
> +if test "z$OS_MAJOR_VERSION" = z10; then
right now, I either build on Catalina which is 10
or Big Sur, which is 11+
These tests are sufficient to target the correct TCC schema

2021-03-29 13:56 UTC, peterheja-bitrise commented on roles/xcode/files/enable_accessibility.sh
> +if test "z$OS_MAJOR_VERSION" = z10; then
Yeah, you do, but 10.3.x and some from the 11.*. line is Mojave.

2021-03-29 13:58 UTC, bitrise-tom commented on roles/xcode/files/enable_accessibility.sh
> +if test "z$OS_MAJOR_VERSION" = z10; then
No. This is the operating system version, not the Xcode version
10.14 is mojave
10.15 is catalina
11.X is the versions of Big Sur we are using

2021-03-29 14:00 UTC, peterheja-bitrise commented on roles/xcode/files/enable_accessibility.sh
> +if test "z$OS_MAJOR_VERSION" = z10; then
? Yes, I know.
I'm saying that 10.x uses Mojave, 10.14, not Catalina.
So you might be okay (on Catalina), but this TCC is working on Catalina only, as far as I know (possibly breaks Mojave / does some undefined behaviour).

2021-03-29 14:19 UTC, bitrise-tom commented on roles/xcode/files/enable_accessibility.sh
> +if test "z$OS_MAJOR_VERSION" = z10; then
We have 1 mojave stack, the rest are catalina and 1 big sur
https://github.com/jacobsalmela/tccutil/blob/main/tccutil.py#L130
The schema for the TDD db is the same for Mojave and Catalina.

2021-03-29 14:22 UTC, bitrise-tom commented on roles/xcode/tasks/main.yml
> +  script: enable_accessibility.sh '{{ ansible_distribution_version }}'
why what?

2021-03-29 14:23 UTC, bitrise-tom commented on roles/xcode/tasks/main.yml
> +  register: xcode_select_selected
as you may see, this is a boolean check on the symlink path

2021-03-30 08:49 UTC, peterheja-bitrise commented on roles/xcode/files/enable_accessibility.sh
> +if test "z$OS_MAJOR_VERSION" = z10; then
Okay.

2021-03-30 08:49 UTC, peterheja-bitrise commented on roles/xcode/tasks/main.yml
> +  script: enable_accessibility.sh '{{ ansible_distribution_version }}'
Why switched which line this is? This is a no op change.

2021-03-30 09:11 UTC, bitrise-tom commented on roles/xcode/tasks/main.yml
> +  script: enable_accessibility.sh '{{ ansible_distribution_version }}'
oh, i see.
Consistency. 
If a command needs a `become: true` I make it the first element, so they are really easy to pick out.

I feel a style guide coming on

2021-03-30 09:24 UTC, tamas-bitrise submitted a review, later dismissed

2021-03-30 09:26 UTC, fehersanyi-bitrise submitted a review, later dismissed

2021-03-30 09:29 UTC, nagypeterjob approved these changes

2021-03-30 10:04 UTC, tamas-bitrise approved these changes

2021-03-30 10:46 UTC, fehersanyi-bitrise approved these changes

2021-03-30 11:10 UTC, peterheja-bitrise approved these changes
LGTM

2021-03-30 11:13 UTC, merged