Flutter to fvm transition
bitrise-io/osx-box-bootstrap pull request #484
Opened 2021-05-20 13:02 UTC by nagypeterjob

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2021-05-20 13:06 UTC, nagypeterjob commented on roles/flutter/tasks/main.yml
>        dest: "~{{ param_user }}/profile.d/flutter.sh"
Can we lose the tilde & go with OS specific user location?

2021-05-20 13:07 UTC, nagypeterjob commented on roles/flutter/tasks/main.yml
> +    path: "/usr/local/flutter"
I am pretty sure that on MacOS, the correct location would be /usr/local/bin/flutter

2021-05-20 13:10 UTC, nagypeterjob commented on roles/flutter/tasks/main.yml
> +  shell: bash -l -c "/home/linuxbrew/.linuxbrew/bin/fvm global {{ flutter_versions[0] }}" # complete version is required
can we put /home/linuxbrew/.linuxbrew/bin/fvm to a variable?

2021-05-20 13:10 UTC, nagypeterjob commented
What I don't understand: Is this a linux only role? I don't see any indication of that

2021-05-20 13:12 UTC, peterheja-bitrise commented on roles/flutter/tasks/main.yml
> +    path: "/usr/local/flutter"
Yup, plus `homebrew uninstall` is the clean version
But shouldn't break how it breaks now

2021-05-20 13:13 UTC, martonszasz-bitrise commented on roles/flutter/tasks/main.yml
>        dest: "~{{ param_user }}/profile.d/flutter.sh"
As discussed with @fehersanyi-bitrise, paths are going to be the subject of final cleanup after we got this thing working, but sure.

2021-05-20 13:13 UTC, peterheja-bitrise commented on roles/flutter/tasks/main.yml
> +  shell: bash -l -c "/home/linuxbrew/.linuxbrew/bin/fvm global {{ flutter_versions[0] }}" # complete version is required
https://github.com/bitrise-io/osx-box-bootstrap/pull/484/files#diff-45ba7edcfad8e75d839dd9602f79eef79dfb4f25c40244609b17ef822d2df8c4R4 PATH is setup correctly

2021-05-20 13:14 UTC, martonszasz-bitrise commented on roles/flutter/tasks/main.yml
> +    path: "/usr/local/flutter"
Same as before - paths are to be fixed / integrated into both MacOS and Linux envs after I got a clear run.

2021-05-20 13:19 UTC, peterheja-bitrise commented on roles/flutter/tasks/main.yml
> +    path: "/usr/local/flutter"
Sorry, I was wrong here.

2021-05-20 13:36 UTC, peterheja-bitrise commented on roles/flutter/tasks/main.yml
> +  shell: bash -l -c "/home/linuxbrew/.linuxbrew/bin/fvm global {{ flutter_versions[0] }}" # complete version is required
Although, yeah, we should set in flutter profile to point to the right flutter, e.g macOS export this to PATH: `/Users/vagrant/fvm/default/bin` which is basically `$HOME/fvm/default/bin`

2021-05-20 13:37 UTC, peterheja-bitrise commented on roles/flutter/tasks/main.yml
> +  shell: bash -l -c "/home/linuxbrew/.linuxbrew/bin/fvm global {{ flutter_versions[0] }}" # complete version is required
I might even go as far as that Linuxbrew might not be properly supported with `fvm` - that's not so surreal either.

2021-05-20 13:48 UTC, peterheja-bitrise commented on roles/flutter/tasks/main.yml
> +  shell: bash -l -c "/home/linuxbrew/.linuxbrew/bin/fvm global {{ flutter_versions[0] }}" # complete version is required
Btw, on a box:
```vagrant@prd-atl-std-y-xcode-12-4-210520131845-s5fmNZPvpTaP4x2SNFGtUn ~ % export PATH="/Users/vagrant/fvm/default/bin:${PATH}"
vagrant@prd-atl-std-y-xcode-12-4-210520131845-s5fmNZPvpTaP4x2SNFGtUn ~ % flutter --version
Flutter 1.26.0-17.8.pre • channel unknown • unknown source
Framework • revision 044f2cf560 (3 months ago) • 2021-02-24 13:02:05 -0800
Engine • revision 042c82b02c
Tools • Dart 2.12.0 (build 2.12.0-259.16.beta)
vagrant@prd-atl-std-y-xcode-12-4-210520131845-s5fmNZPvpTaP4x2SNFGtUn ~ % fvm list | grep 2.0.5
2.0.5
vagrant@prd-atl-std-y-xcode-12-4-210520131845-s5fmNZPvpTaP4x2SNFGtUn ~ % fvm global 2.0.5
Flutter "2.0.5" has been set as global
vagrant@prd-atl-std-y-xcode-12-4-210520131845-s5fmNZPvpTaP4x2SNFGtUn ~ % flutter --version
Flutter 2.0.5 • channel unknown • unknown source
Framework • revision adc687823a (5 weeks ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3
```

So it seems to work, if PATH is correct.

2021-05-21 14:02 UTC, nagypeterjob commented on roles/flutter/vars/main.yml
> +FVM_HOME: "{{ \"/home/linuxbrew/fvm/default/bin\" if (ansible_os_family == 'Debian') else \"~/fvm/default/bin\" if (ansible_os_family == 'Darwin') else \"\" }}"
one last suggestion: can we loose the ~ here?

2021-05-21 14:07 UTC, fehersanyi-bitrise requested changes

2021-05-21 14:07 UTC, fehersanyi-bitrise commented on roles/flutter/files/flutter.sh
> +# export PATH="$PATH":"$HOME/fvm/default/bin"
why is this commented out?

2021-05-21 14:07 UTC, fehersanyi-bitrise commented on roles/flutter/tasks/main.yml
> +- name: Tap and install dart
if we brew install flutter then I don't think this will be necessary

2021-05-21 14:37 UTC, peterheja-bitrise commented on roles/flutter/vars/main.yml
> +FVM_HOME: "{{ \"/home/linuxbrew/fvm/default/bin\" if (ansible_os_family == 'Debian') else \"~/fvm/default/bin\" if (ansible_os_family == 'Darwin') else \"\" }}"
You mean replace it with a `$HOME` or similar?

2021-05-21 14:37 UTC, peterheja-bitrise commented on roles/flutter/tasks/main.yml
> +- name: Tap and install dart
fvm depends on dart

2021-05-21 14:38 UTC, nagypeterjob commented on roles/flutter/vars/main.yml
> +FVM_HOME: "{{ \"/home/linuxbrew/fvm/default/bin\" if (ansible_os_family == 'Debian') else \"~/fvm/default/bin\" if (ansible_os_family == 'Darwin') else \"\" }}"
exactly

2021-05-26 08:58 UTC, nagypeterjob commented on roles/flutter/tasks/main.yml
>        dest: "~{{ param_user }}/profile.d/flutter.sh"
I would really like this ~ to be gone, but other than that looks ok

2021-05-26 10:31 UTC, nagypeterjob commented
Fine by me, I cannot approve my own PR, so @martonszasz-bitrise you can approve it for me :D

2021-05-26 10:54 UTC, fehersanyi-bitrise commented
The test is still failing tho 🤔

2021-05-26 11:45 UTC, martonszasz-bitrise commented
Yes, still trying to find out why the `flutter global` step fails in the test env, when it sets the global flutter in local just fine.

2021-05-28 09:17 UTC, closed without merging